image: toliak/bootstrap-cpp:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

tests:
  script:
    - ./scripts/tests.sh

coverage:
  script:
    - ./scripts/coverage.sh

quality:
  script:
    - ./scripts/duplication.sh

mem_leaks:
  script:
    - ./scripts/valgrind.sh